"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#&q==^cx_&fesyg63zd2e71h3z(zxk5r9+p+u4s)tpew9r6uu*'

# SECURITY WARNING: don't run with debug turned on in production!
# 可用环境变量覆盖：
# - DJANGO_DEBUG=0/1
# - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost,example.com
# - DJANGO_CSRF_TRUSTED_ORIGINS=http://example.com,https://example.com
DEBUG = (os.getenv("DJANGO_DEBUG", "1").strip() not in {"0", "false", "False"})

# 开发/本地测试允许的 Host。
# Django Test Client 默认使用 testserver；不加入会触发 DisallowedHost(400)。
_default_allowed_hosts = ["127.0.0.1", "localhost", "testserver", "8.148.66.166"]
_env_hosts = [h.strip() for h in (os.getenv("DJANGO_ALLOWED_HOSTS") or "").split(",") if h.strip()]
ALLOWED_HOSTS = _env_hosts or _default_allowed_hosts

# 若通过公网域名/IP 访问并需要登录/POST，请配置 CSRF_TRUSTED_ORIGINS。
_env_csrf = [h.strip() for h in (os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS") or "").split(",") if h.strip()]
CSRF_TRUSTED_ORIGINS = _env_csrf or ["http://8.148.66.166:12345", "https://8.148.66.166:12345"]
# Application definition

INSTALLED_APPS = [
    'space_app.apps.SpaceAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# 使用仿真数据库，Django 默认数据库仅占位，不持久化业务数据。
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 会话改用签名 Cookie，避免依赖 django_session 表。
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
